service: prompter-server
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  memorySize: 128
package:
  exclude:
    - venv/**
    - data/**
functions:
  prompter-server:
    handler: index.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
